// const ACCESS_TOKEN = process.env.ACCESS_TOKEN;
// import { TfiControlShuffle } from "react-icons/tfi";
// import { ReactNode,  } from "react";
import baseApi, { apiConfig, ACCESS_TOKEN } from "./baseApi";


export default async function getAllNews(
    category: string
    ): Promise<AllNewsProps> {

    const newsCategory =
        category === "fetchTopRated" ? "movie/top_rated" : "trending/all/week";

    const req = await fetch(baseApi + "/" + newsCategory, apiConfig);

    if (!req.ok) {
        throw Error("failed to fetch news ");
    }
    
    const response = (await req.json()) as unknown;
    return response as AllNewsProps;
    }
    // Generated by https://quicktype.io

    export interface AllNewsProps {
    map(arg0: (news: any) => import("react").JSX.Element): import("react").ReactNode;
    page: number;
    results: Result[];
    total_pages: number;
    total_results: number;
    }

    // export type AllNewsProps {
    // author: string;
    // title: string;
    // description: string;
    // url: string;
    // urlToImage: string;
    // publishedAt: string;
    // content: string;
    // }

    export interface Result {
    author: string;
    title: string;
    description: string;
    url: string;
    urlToImage: string;
    publishedAt: string;
    content: string;
    }

