// const ACCESS_TOKEN = process.env.ACCESS_TOKEN;
// import { TfiControlShuffle } from "react-icons/tfi";
import baseApi, { apiConfig, ACCESS_TOKEN } from "./baseApi";


export default async function getAllNews(
    category: string
    ): Promise<AllNewsProps> {

    const newsCategory =
        category === "fetchTopRated" ? "movie/top_rated" : "trending/all/week";

    const req = await fetch(baseApi + "/" + newsCategory, apiConfig);

    if (!req.ok) {
        throw Error("failed to fetch news ");
    }
    
    const response = (await req.json()) as unknown;
    return response as AllNewsProps;
    }
    // Generated by https://quicktype.io

    export interface AllNewsProps {
    page: number;
    results: Result[];
    total_pages: number;
    total_results: number;
    }

    export interface Result {
    author: string;
    title: string;
    description: string;
    url: string;
    urlToImage: string;
    publishedAt: string;
    content: string;
    }

